# -*- coding: utf-8 -*-
# Part of BrowseInfo. See LICENSE file for full copyright and licensing details.

import bed_transfer
# import ir_attachment
import medical_drugs_recreational
import medical_ambulatory_care_procedure
import medical_appointment
import medical_diagnostic_hypotesis
import medical_diet_belief
import medical_diet_therapeutic
import medical_directions
# import medical_domiciliary_unit
import medical_dose_unit
import medical_drug_form
import medical_drug_route
import medical_ethnicity
import medical_family_code
import medical_family_disease
import medical_genetic_risk
import medical_health_service_line
import medical_health_service
import medical_hospital_bed
import medical_hospital_building
import medical_hospital_oprating_room
import medical_hospital_unit
import medical_hospital_ward
import medical_icu_apache2
import medical_icu_chest_drainage
import medical_icu_ecg
import medical_icu_glasgow
import medical_icu_ventilation
# import medical_imaging_test_request
# import medical_imaging_test_result
# import medical_imaging_test_type
# import medical_imaging_test
import medical_inpatient_diet
import medical_inpatient_icu
import medical_inpatient_medication_admin_time
import medical_inpatient_medication_log
import medical_inpatient_medication
import medical_inpatient_registration
import medical_insurance_plan
import medical_insurance
import medical_lab_test_units
import medical_lab
import medical_medicament
import medical_medication_dosage
import medical_neomatal_apgar
import medical_newborn
import medical_occupation
import medical_operation
import medical_operational_area
import medical_operational_sector
# import medical_paper_archive
import medical_pathology_category
import medical_pathology_group_member
import medical_pathology_group
import medical_pathology
import medical_patient_ambulatory_care_medical_supply
import medical_patient_ambulatory_care_medicament
import medical_patient_ambulatory_care_vaccine
import medical_patient_ambulatory_care
import medical_patient_cage
import medical_patient_colposcopy_history
import medical_patient_disease
import medical_patient_disease1
import medical_patient_diseases
import medical_patient_evaluation
import medical_patient_lab_test
import medical_patient_mammography_history
import medical_patient_medication
import medical_patient_medication1
import medical_patient_menstrual_history
import medical_patient_pap_history
import medical_patient_pregnency
import medical_patient_prental_evolution
import medical_patient_psc
import medical_patient_rounding_medical_supply
import medical_patient_rounding_medicament
import medical_patient_rounding_vaccine
import medical_patient_rounding
import medical_vaccitation
import medical_patient
import medical_pediatrics_growth_charts_who
import medical_perinatal_monitor
import medical_physician
import medical_preinatal
import medical_prescription_line
import medical_prescription_order
import medical_procedure
import medical_puerperium_monitor
import medical_rcri
import medical_rounding_procedure
import medical_secondary_condition
import medical_signs_and_sympotoms
import medical_speciality
import medical_surgery
import medical_test_critearea
import medical_test_type
import medicament_category
# import pet_breed
# import pet_type
import psc_code
import res_partner
import stock_move


# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:s